<?php

/**
 * @file
 * Hook implementations for the Recipes module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 *
 * This alters all node forms because we don't know the machine name of the
 * recipe content type that the students created :(
 */
function recipes_form_node_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['actions']['publish']['#submit'][] = 'recipes_node_rezept_submit';
}

/**
 * Additional submit callback for the rezept form.
 */
function recipes_node_rezept_submit($form, FormStateInterface $form_state) {
  drpal_set_message(t('Thank you for submitting your recipe!'));
}

/**
 * Implements hook_prepprocess_TEMPLATE for the "node" template.
 */
function recipes_preprocess_node(&$variables) {
  $config = \Drupal::config('recipes.settings');

  // @todo: Add a boolean variable 'show_message' to the twig variables.

  // Add cacheability metadata to ensure config changes are reflected.
  $cache_extras = [];
  \Drupal\Core\Render\BubbleableMetadata::createFromObject($config)
    ->applyTo($cache_extras);
  render($cache_extras);
}
