# Schema for the configuration files of the recipes module.

recipes.settings:
  type: config_object
  label: 'Recipes settings'
  mapping:
    show_message:
      type: boolean
      label: 'Show message on recipes'
